-- Agent architecture + agentic engineering strategy articles

insert into articles (title, url, description, author, source) values
('Scaling Managed Agents: Decoupling the brain from the hands',
 'https://www.anthropic.com/engineering/managed-agents',
 'Anthropic''s framework for agent systems that separate planning from execution, so each layer can scale independently.',
 'Anthropic',
 'Anthropic'),
('Trustworthy agents in practice',
 'https://www.anthropic.com/research/trustworthy-agents',
 'Anthropic research on building agents that do the right thing, including how to handle ambiguity and recover from failure.',
 'Anthropic',
 'Anthropic'),
('Demystifying evals for AI agents',
 'https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents',
 'A practical guide to evaluating agent behaviour when traditional benchmarks do not apply.',
 'Anthropic',
 'Anthropic'),
('The Anatomy of an Agent Harness',
 'https://blog.langchain.com/the-anatomy-of-an-agent-harness',
 'LangChain breaks down the moving parts in a production agent system: models, tools, memory, and orchestration.',
 'LangChain',
 'LangChain Blog'),
('Components of a Coding Agent',
 'https://magazine.sebastianraschka.com/p/components-of-a-coding-agent',
 'Sebastian Raschka walks through the architecture of coding agents, from context management to tool use.',
 'Sebastian Raschka',
 'Ahead of AI'),
('Skill Issue: Harness Engineering for Coding Agents',
 'https://www.hlyr.dev/blog/skill-issue-harness-engineering-for-coding-agents',
 'Why the harness around the model matters more than the model itself, with concrete engineering examples.',
 'Kyle',
 'hlyr.dev'),
('The 8 Levels of Agentic Engineering',
 'https://www.bassimeledath.com/blog/levels-of-agentic-engineering',
 'A ladder for benchmarking how far an organisation has gone with agent engineering, from zero to fully autonomous.',
 'Bassim Eledath',
 'bassimeledath.com'),
('What is agentic engineering?',
 'https://simonwillison.net/guides/agentic-engineering-patterns/what-is-agentic-engineering/',
 'Simon Willison''s definition of the field, and why he thinks it is genuinely new rather than rebranded tooling.',
 'Simon Willison',
 'simonwillison.net'),
('Agent Responsibly',
 'https://sebastiandedeyne.com/agent-responsibly/',
 'Practical constraints and patterns for giving agents just enough autonomy without catastrophic failure modes.',
 'Sebastian De Deyne',
 'sebastiandedeyne.com');
