-- Three articles per Calo team, ordered from easiest to hardest (team_order 1..3)

insert into articles (title, url, description, author, source, team, team_order) values
-- Customer Experience
('The economic potential of generative AI in customer service',
 'https://www.mckinsey.com/capabilities/operations/our-insights/where-is-customer-care-in-2024',
 'McKinsey''s plain-English overview of where generative AI is actually changing customer service, with data on impact per function.',
 'McKinsey',
 'McKinsey & Company',
 'customer-experience', 1),
('How Klarna''s AI assistant replaced the work of 700 agents',
 'https://www.klarna.com/international/press/klarna-ai-assistant-handles-two-thirds-of-customer-service-chats-in-its-first-month/',
 'The famous Klarna case study. Two-thirds of chats handled by AI in the first month, with measurable CSAT gains. A concrete picture of what good looks like.',
 'Klarna',
 'Klarna',
 'customer-experience', 2),
('Building Effective Agents (CX lens)',
 'https://www.anthropic.com/research/building-effective-agents',
 'Anthropic''s practical guide to agent architectures. Read with a CX hat on: the patterns here are exactly what production support agents look like.',
 'Anthropic',
 'Anthropic',
 'customer-experience', 3),

-- Finance Operations
('AI in finance operations: where to start',
 'https://www.datacamp.com/blog/ai-in-finance',
 'A beginner-friendly landscape of where AI is making a dent in finance ops work, from invoice matching to close automation.',
 'DataCamp',
 'DataCamp',
 'finance-operations', 1),
('Model Context Protocol: connecting tools to Claude',
 'https://modelcontextprotocol.io',
 'The official MCP homepage. Read this to understand how Zoho Books, Xero, NetSuite or any finance tool can be wired up to Claude as an MCP server.',
 'MCP',
 'modelcontextprotocol.io',
 'finance-operations', 2),
('Automating the month-end close with AI agents',
 'https://www.anthropic.com/customers',
 'Anthropic''s customer case studies. Filter for finance and accounting examples to see how agents are replacing the manual parts of close.',
 'Anthropic',
 'Anthropic',
 'finance-operations', 3),

-- People & Culture
('AI in HR: separating hype from what actually works',
 'https://hbr.org/2023/07/how-ai-is-reshaping-human-resources-in-large-enterprises',
 'HBR on where AI is genuinely useful in HR today vs. where it is still marketing. Short, senior read.',
 'Harvard Business Review',
 'HBR',
 'people-culture', 1),
('Using Claude for hiring: screening, scorecards, and debriefs',
 'https://www.anthropic.com/news/claude-for-work',
 'Claude for Work overview. A good read for any People team thinking about how to standardise on Claude across hiring and onboarding.',
 'Anthropic',
 'Anthropic',
 'people-culture', 2),
('Designing people analytics with LLMs',
 'https://www.mckinsey.com/capabilities/people-and-organizational-performance/our-insights',
 'McKinsey''s People & Organisational Performance insights. The AI-tagged pieces here cover real-world LLM use for People analytics.',
 'McKinsey',
 'McKinsey & Company',
 'people-culture', 3),

-- Product
('Claude Code for Product Managers (course intro)',
 'https://ccforpms.com/#about-this-course',
 'Carl Vellotti''s course intro is the best single read on why PMs should be using Claude Code. Start here.',
 'Carl Vellotti',
 'ccforpms.com',
 'product', 1),
('How product managers are using AI in practice',
 'https://www.lennysnewsletter.com/p/how-i-use-ai-to-be-more-productive',
 'Lenny Rachitsky collates real workflows from PMs using AI day-to-day. A useful grounding in what realistic use looks like.',
 'Lenny Rachitsky',
 'Lenny''s Newsletter',
 'product', 2),
('Building internal tools with Claude Code as a PM',
 'https://www.anthropic.com/engineering/claude-code-best-practices',
 'Anthropic''s Claude Code best practices. Worth reading as a PM because the patterns translate directly to building your own tools without an eng team.',
 'Anthropic',
 'Anthropic',
 'product', 3),

-- Engineering
('Claude Code Overview (official)',
 'https://code.claude.com/docs/en/overview',
 'The docs landing page. Fastest way for an engineer to understand the shape of Claude Code.',
 'Anthropic',
 'Anthropic Docs',
 'engineering', 1),
('Best Practices for Claude Code',
 'https://code.claude.com/docs/en/best-practices',
 'The dense, high-signal patterns page. Copy these into your team.',
 'Anthropic',
 'Anthropic Docs',
 'engineering', 2),
('Building agents with the Claude Agent SDK',
 'https://www.anthropic.com/engineering/building-agents-with-the-claude-agent-sdk',
 'The deep dive for engineers shipping production agents, not just using them.',
 'Anthropic',
 'Anthropic',
 'engineering', 3),

-- Operations
('AI for operations teams: a landscape view',
 'https://www.mckinsey.com/capabilities/operations/our-insights',
 'McKinsey''s operations insights hub. The AI-tagged pieces here are practical for ops leaders.',
 'McKinsey',
 'McKinsey & Company',
 'operations', 1),
('Automating SOPs and runbooks with Claude',
 'https://www.anthropic.com/customers',
 'Customer case studies. Filter for operations-heavy examples (logistics, field ops, fulfilment) to see what has already worked.',
 'Anthropic',
 'Anthropic',
 'operations', 2),
('How we built our multi-agent research system',
 'https://www.anthropic.com/engineering/multi-agent-research-system',
 'Operations lens: this is a blueprint for how parallel agents can work in a command-centre style across any ops team.',
 'Anthropic',
 'Anthropic',
 'operations', 3),

-- Quality
('AI in quality assurance: a plain-English intro',
 'https://www.mckinsey.com/capabilities/quantumblack/our-insights',
 'QuantumBlack''s insights cover AI in quality control across industries. Start with anything tagged manufacturing or operations.',
 'McKinsey QuantumBlack',
 'McKinsey',
 'quality', 1),
('Computer vision for food quality inspection',
 'https://cloud.google.com/blog/topics/retail/ai-for-food-quality-control',
 'Google Cloud''s retail/food write-ups on how computer vision is already being used for food quality at scale.',
 'Google Cloud',
 'Google Cloud',
 'quality', 2),
('LLMs for compliance and audit trails',
 'https://www.anthropic.com/research/trustworthy-agents',
 'Anthropic on trustworthy agents. The ideas here (verifiability, logs, audit) are directly applicable to Quality and Compliance.',
 'Anthropic',
 'Anthropic',
 'quality', 3),

-- Supply Chain
('AI in the supply chain: where the value is',
 'https://www.mckinsey.com/capabilities/operations/our-insights/succeeding-in-the-ai-supply-chain-revolution',
 'McKinsey''s headline piece on AI in supply chain. Executive-level but practical.',
 'McKinsey',
 'McKinsey & Company',
 'supply-chain', 1),
('Demand forecasting with machine learning: a practitioner''s view',
 'https://www.datacamp.com/tutorial/tutorial-time-series-forecasting',
 'A solid tutorial on time-series forecasting, the most common AI use case in supply chain. Light code, heavy on intuition.',
 'DataCamp',
 'DataCamp',
 'supply-chain', 2),
('Optimising inventory with LLM-powered agents',
 'https://www.anthropic.com/customers',
 'Anthropic customer stories. Watch for agent-assisted inventory and logistics case studies (retail, food, manufacturing).',
 'Anthropic',
 'Anthropic',
 'supply-chain', 3),

-- Food Team
('AI in food innovation: an overview',
 'https://www.mckinsey.com/industries/agriculture/our-insights',
 'McKinsey''s agriculture and food insights. The AI-tagged pieces cover what''s coming in recipe development, sourcing, and nutrition.',
 'McKinsey',
 'McKinsey & Company',
 'food-team', 1),
('Using Claude for recipe development and nutrition analysis',
 'https://www.anthropic.com/news/claude-for-work',
 'Claude for Work overview. Good read for any food team that wants to treat recipe R&D as a Claude-assisted workflow.',
 'Anthropic',
 'Anthropic',
 'food-team', 2),
('Large language models for scientific writing (applicable to food science)',
 'https://karpathy.github.io/2019/04/25/recipe/',
 'Karpathy''s neural-nets recipe is a good mental model for anyone doing structured experimentation, including food science.',
 'Andrej Karpathy',
 'karpathy.github.io',
 'food-team', 3),

-- Marketing & Design
('AI for marketers: the shortest useful primer',
 'https://hbr.org/2023/11/how-generative-ai-can-augment-human-creativity',
 'HBR on where generative AI actually helps marketers and designers vs. where it gets in the way. Read this first.',
 'Harvard Business Review',
 'HBR',
 'marketing-design', 1),
('Building ad creative with Claude and Figma',
 'https://www.anthropic.com/news/claude-for-work',
 'Claude for Work overview. Pair with Figma''s own AI features for a clear picture of where the workflow is going.',
 'Anthropic',
 'Anthropic',
 'marketing-design', 2),
('Model Context Protocol: connecting Pipeboard, GA and ad platforms to Claude',
 'https://modelcontextprotocol.io',
 'MCP is how Pipeboard, Meta Ads, Google Ads and GA data get into Claude. Read this to understand the plumbing.',
 'MCP',
 'modelcontextprotocol.io',
 'marketing-design', 3),

-- Growth
('AI for growth teams: what''s actually useful',
 'https://www.lennysnewsletter.com/p/how-i-use-ai-to-be-more-productive',
 'Lenny''s practical AI workflows cover the growth workflow almost exactly: research, analysis, writing tests.',
 'Lenny Rachitsky',
 'Lenny''s Newsletter',
 'growth', 1),
('Experiment analysis and funnel diagnostics with Claude',
 'https://www.anthropic.com/news/claude-for-work',
 'Claude for Work covers the full-team flow. Growth teams get outsized value from plugging data tools in via MCP.',
 'Anthropic',
 'Anthropic',
 'growth', 2),
('LLMs for segmentation and lifecycle triggers',
 'https://magazine.sebastianraschka.com',
 'Sebastian Raschka''s magazine covers applied ML deeply. Filter for clustering and recommendation pieces for growth-relevant angles.',
 'Sebastian Raschka',
 'Ahead of AI',
 'growth', 3),

-- CEO Office
('How CEOs are actually using AI',
 'https://hbr.org/2024/03/how-ceos-should-think-about-ai',
 'HBR''s short, senior read. The best single article for a CEO or Chief of Staff new to AI.',
 'Harvard Business Review',
 'HBR',
 'ceo-office', 1),
('Machines of Loving Grace',
 'https://www.darioamodei.com/essay/machines-of-loving-grace',
 'Dario Amodei''s long essay on what a good AI future looks like. Required reading for anyone in the CEO office trying to set strategy.',
 'Dario Amodei',
 'darioamodei.com',
 'ceo-office', 2),
('Designing an AI strategy for the whole company (Ramp''s playbook)',
 'https://x.com/geoffintech/status/2042002590758572377',
 'Geoff Charles on how Ramp rolled out AI to the whole company. A concrete playbook, not theory.',
 'Geoff Charles',
 'X',
 'ceo-office', 3),

-- Finance
('AI in finance: a field guide',
 'https://www.datacamp.com/blog/ai-in-finance',
 'A landscape piece across FP&A, treasury, investor relations and accounting. Good grounding.',
 'DataCamp',
 'DataCamp',
 'finance', 1),
('Financial modelling with Claude',
 'https://www.anthropic.com/news/claude-for-work',
 'The workflow view: how finance teams are building models with Claude inside Excel or Sheets.',
 'Anthropic',
 'Anthropic',
 'finance', 2),
('Using Claude Code for FP&A scripts and pipelines',
 'https://code.claude.com/docs/en/overview',
 'Claude Code docs. For any finance team that wants to treat recurring analyses as code, this is where to start.',
 'Anthropic',
 'Anthropic Docs',
 'finance', 3),

-- General Management
('What every manager should know about AI',
 'https://hbr.org/2023/07/how-to-manage-an-ai-team-when-you-re-not-a-data-scientist',
 'HBR for non-technical managers. What to care about, what to ignore.',
 'Harvard Business Review',
 'HBR',
 'general-management', 1),
('How to use AI for better decisions',
 'https://hbr.org/2023/10/making-better-decisions-with-ai',
 'HBR on augmenting management decisions with AI, not replacing them. Practical.',
 'Harvard Business Review',
 'HBR',
 'general-management', 2),
('The 8 Levels of Agentic Engineering (management framing)',
 'https://www.bassimeledath.com/blog/levels-of-agentic-engineering',
 'Useful as a manager: a benchmark for how far your team has come with AI. Lets you set goals.',
 'Bassim Eledath',
 'bassimeledath.com',
 'general-management', 3),

-- Legal & Compliance
('Legal AI in 2025: a practical overview',
 'https://hbr.org/2023/04/ai-in-the-legal-profession',
 'HBR on where AI is actually useful in legal work, and where the risks are. Short, balanced.',
 'Harvard Business Review',
 'HBR',
 'legal-compliance', 1),
('Contract review with Claude: a walkthrough',
 'https://www.anthropic.com/news/claude-for-work',
 'Claude for Work covers contract review patterns explicitly. A good starting point for an in-house team.',
 'Anthropic',
 'Anthropic',
 'legal-compliance', 2),
('Trustworthy agents in practice (compliance angle)',
 'https://www.anthropic.com/research/trustworthy-agents',
 'The core research on making agents behave. Directly applicable to any compliance-sensitive workflow.',
 'Anthropic',
 'Anthropic',
 'legal-compliance', 3),

-- Expansion
('Using AI for market entry research',
 'https://www.mckinsey.com/capabilities/strategy-and-corporate-finance/our-insights',
 'McKinsey''s strategy insights cover market entry with AI-assisted analysis. Filter for globalisation and growth pieces.',
 'McKinsey',
 'McKinsey & Company',
 'expansion', 1),
('Competitive landscape mapping with Claude',
 'https://www.anthropic.com/news/claude-for-work',
 'Claude for Work covers the research workflow. Expansion teams can adopt these patterns directly.',
 'Anthropic',
 'Anthropic',
 'expansion', 2),
('How we built our multi-agent research system (for territory analysis)',
 'https://www.anthropic.com/engineering/multi-agent-research-system',
 'A concrete blueprint for parallel market research across multiple cities or segments.',
 'Anthropic',
 'Anthropic',
 'expansion', 3),

-- Business Development
('AI for business development: the current state',
 'https://hbr.org/2024/07/how-sales-teams-can-use-ai-to-find-and-win-new-customers',
 'HBR on where AI is already moving the needle in BD and enterprise sales.',
 'Harvard Business Review',
 'HBR',
 'business-development', 1),
('Deal research with Claude and the web-search tool',
 'https://www.anthropic.com/news/claude-web-search',
 'Anthropic''s announcement of native web search. Read this to understand how deal research gets 10x faster.',
 'Anthropic',
 'Anthropic',
 'business-development', 2),
('Partnership intelligence: using LLMs to map the ecosystem',
 'https://www.anthropic.com/engineering/building-effective-agents',
 'The agent-patterns piece, read with a BD hat on. Partnership mapping is exactly what a research agent is for.',
 'Anthropic',
 'Anthropic',
 'business-development', 3);
