-- Bulk seed: 20 articles, 10 podcasts (as articles), 10 courses

-- 20 articles
insert into articles (title, url, description, author, source) values
('Claude Code Overview',
 'https://code.claude.com/docs/en/overview',
 'The official docs landing page for Claude Code. Start here to understand what it is and how it fits your workflow.',
 'Anthropic',
 'Anthropic Docs'),
('Claude Code Tutorial for Beginners: Complete Getting Started Guide',
 'https://www.nxcode.io/resources/news/claude-code-tutorial-beginners-guide-2026',
 'A hand-held walkthrough of installing Claude Code and running your first meaningful commands in 2026.',
 'NxCode',
 'nxcode.io'),
('Getting Started with Claude Code: A Researcher''s Setup Guide',
 'https://paulgp.substack.com/p/getting-started-with-claude-code',
 'A researcher''s view of setting up Claude Code for real work, not toy demos.',
 'Paul Goldsmith-Pinkham',
 'Substack'),
('Claude Code: A Guide With Practical Examples',
 'https://www.datacamp.com/tutorial/claude-code',
 'DataCamp''s tour of Claude Code with concrete coding scenarios you can follow along with.',
 'Bex Tuychiev',
 'DataCamp'),
('How to Use Anthropic Claude for Blogging, Full Guide 2026',
 'https://neuraplus-ai.github.io/blog/how-to-use-anthropic-claude-for-blogging.html',
 'Practical patterns for using Claude as a writing collaborator, from draft to polish.',
 'NeuraPulse',
 'neuraplus-ai'),
('Claude Cowork',
 'https://www.anthropic.com/product/claude-cowork',
 'Anthropic''s product page for Cowork, the desktop agent that works across your files and apps.',
 'Anthropic',
 'Anthropic'),
('Claude Cowork Tutorial: How to Use Anthropic''s AI Desktop Agent',
 'https://www.datacamp.com/tutorial/claude-cowork-tutorial',
 'Step-by-step tour of Claude Cowork with screenshots of what it can actually do on your machine.',
 'DataCamp',
 'DataCamp'),
('Anthropic launches Cowork, a Claude Desktop agent that works in your files',
 'https://venturebeat.com/technology/anthropic-launches-cowork-a-claude-desktop-agent-that-works-in-your-files-no',
 'Launch coverage of Claude Cowork. What''s new and why Anthropic built it.',
 'VentureBeat',
 'VentureBeat'),
('Introducing Agent Skills',
 'https://claude.com/blog/skills',
 'Anthropic''s announcement of skills. The shortest read to understand what they are and why they matter.',
 'Anthropic',
 'Anthropic'),
('Equipping Agents for the Real World with Agent Skills',
 'https://www.anthropic.com/engineering/equipping-agents-for-the-real-world-with-agent-skills',
 'The engineering post on how skills fit into building agents that do useful work in production.',
 'Anthropic',
 'Anthropic'),
('Claude Skills are awesome, maybe a bigger deal than MCP',
 'https://simonw.substack.com/p/claude-skills-are-awesome-maybe-a',
 'Simon Willison argues that skills are a quietly bigger unlock than MCP. Persuasive.',
 'Simon Willison',
 'Substack'),
('Skills for Claude Code: The Ultimate Guide from an Anthropic Engineer',
 'https://medium.com/@tort_mario/skills-for-claude-code-the-ultimate-guide-from-an-anthropic-engineer-bcd66faaa2d6',
 'A long-form guide to building and organising skills in Claude Code, written by an Anthropic engineer.',
 'Mario Tort',
 'Medium'),
('Anthropic Just Released a 32-Page Playbook for Building Claude Skills',
 'https://medium.com/@AdithyaGiridharan/anthropic-just-released-a-32-page-playbook-for-building-claude-skills-heres-what-you-need-to-b86fe0b123ae',
 'A digest of Anthropic''s official playbook for building skills, with the key takeaways if you won''t read all 32 pages.',
 'Adithya Giridharan',
 'Medium'),
('Discover and install prebuilt plugins through marketplaces',
 'https://code.claude.com/docs/en/discover-plugins',
 'How to browse and install plugins from Claude Code''s marketplace.',
 'Anthropic',
 'Anthropic Docs'),
('How to Build Claude Code Plugins: A Step-by-Step Guide',
 'https://www.datacamp.com/tutorial/how-to-build-claude-code-plugins',
 'Build your first Claude Code plugin end to end, from scaffold to install.',
 'DataCamp',
 'DataCamp'),
('Best Practices for Claude Code',
 'https://code.claude.com/docs/en/best-practices',
 'Anthropic''s official best-practice guide. Dense with patterns you''ll want to copy.',
 'Anthropic',
 'Anthropic Docs'),
('How we built our multi-agent research system',
 'https://www.anthropic.com/engineering/multi-agent-research-system',
 'Anthropic''s engineering team on how they architected a multi-agent research system, with the failure modes they hit.',
 'Anthropic',
 'Anthropic'),
('Building agents with the Claude Agent SDK',
 'https://www.anthropic.com/engineering/building-agents-with-the-claude-agent-sdk',
 'The deep dive on the Claude Agent SDK and what you can build with it.',
 'Anthropic',
 'Anthropic'),
('Claude''s Context Engineering Secrets: Best Practices Learned from Anthropic',
 'https://01.me/en/2025/12/context-engineering-from-claude/',
 'A careful read on the context engineering patterns that make Anthropic''s own apps fast and reliable.',
 'Bojie Li',
 '01.me'),
('Machines of Loving Grace',
 'https://www.darioamodei.com/essay/machines-of-loving-grace',
 'Dario Amodei''s essay on what a good AI future could look like. Required reading if you want to think seriously about where this is going.',
 'Dario Amodei',
 'darioamodei.com');

-- 10 podcasts, stored as articles with source = 'Podcast'
insert into articles (title, url, description, author, source) values
('AI + a16z',
 'https://open.spotify.com/show/3bz8jF49EasFo2YZVOQDUW',
 'Andreessen Horowitz''s show on where AI is going, aimed at the investor and builder audience.',
 'a16z',
 'Podcast'),
('All-In',
 'https://open.spotify.com/show/2IqXAVFR4e0Bmyjsdc8QzF',
 'Chamath, Jason Calacanis, David Sacks and David Friedberg on tech, politics and markets. AI features heavily.',
 'Chamath, Jason, Sacks, Friedberg',
 'Podcast'),
('Dwarkesh Podcast',
 'https://open.spotify.com/show/4JH4tybY1zX6e5hjCwU6gF',
 'Long-form interviews with AI researchers and operators. Deep, technical, patient.',
 'Dwarkesh Patel',
 'Podcast'),
('Latent Space: The AI Engineer Podcast',
 'https://open.spotify.com/show/2p7zZVwVF6Yk0Zsb4QmT7t',
 'Swyx and Alessio cover the AI engineering frontier. Closest show to the actual code.',
 'Swyx & Alessio',
 'Podcast'),
('No Priors',
 'https://open.spotify.com/show/0O65xhqvGVhpgdIrrdlEYk',
 'Sarah Guo and Elad Gil interview the people building the AI stack.',
 'Sarah Guo & Elad Gil',
 'Podcast'),
('Lex Fridman Podcast',
 'https://open.spotify.com/show/2MAi0BvDc6GTFvKFPXnkCL',
 'Long-form interviews with AI researchers, CEOs, and thinkers. Slow burn but substantial.',
 'Lex Fridman',
 'Podcast'),
('Hard Fork',
 'https://open.spotify.com/show/44fllCS2FTFr2x2kjP9xeT',
 'Kevin Roose and Casey Newton (NYT) make AI news digestible and occasionally funny.',
 'Kevin Roose & Casey Newton',
 'Podcast'),
('Lenny''s Podcast',
 'https://open.spotify.com/show/2dR1MUZEHCOnz1LVfNac0j',
 'A product-management lens on AI. Useful if you care about shipping AI features, not just theory.',
 'Lenny Rachitsky',
 'Podcast'),
('The AI Daily Brief',
 'https://open.spotify.com/show/7gKwwMLFLc6RmjmRpbMtEO',
 'NLW''s daily digest of AI news. The quickest way to stay current.',
 'Nathaniel Whittemore',
 'Podcast'),
('The Cognitive Revolution',
 'https://open.spotify.com/show/6yHyok3M3BjqzR0VB5MSyk',
 'Nathan Labenz and Erik Torenberg on the big AI shifts, with strong operator guests.',
 'Nathan Labenz & Erik Torenberg',
 'Podcast');

-- 10 courses
insert into courses (title, url, description, provider, estimated_hours) values
('Claude 101',
 'https://anthropic.skilljar.com/',
 'Anthropic''s official entry-level course. Free, with a certificate. The recommended first step.',
 'Anthropic',
 2),
('Google AI Essentials',
 'https://grow.google/ai-essentials/',
 'Google''s practical intro to using AI at work. About five hours, available on Coursera.',
 'Google',
 5),
('Elements of AI',
 'https://www.elementsofai.com/',
 'University of Helsinki''s free, no-code intro to AI concepts. Strong for non-technical audiences.',
 'University of Helsinki',
 30),
('Introduction to Claude Cowork',
 'https://anthropic.skilljar.com/',
 'Anthropic''s course on getting productive with Cowork as a non-developer.',
 'Anthropic',
 1),
('Introduction to Agent Skills',
 'https://anthropic.skilljar.com/introduction-to-agent-skills',
 'Anthropic''s course on what skills are and how to use them effectively.',
 'Anthropic',
 1),
('Claude Code in Action',
 'https://anthropic.skilljar.com/claude-code-in-action',
 'Anthropic''s hands-on course for Claude Code. About an hour.',
 'Anthropic',
 1),
('Building with the Claude API',
 'https://anthropic.skilljar.com/',
 'The deepest Anthropic course. Eight-plus hours covering the full API surface.',
 'Anthropic',
 8),
('Introduction to Model Context Protocol (MCP)',
 'https://anthropic.skilljar.com/',
 'Anthropic''s course on MCP, the protocol that lets models talk to external tools.',
 'Anthropic',
 1),
('Agentic AI with Andrew Ng',
 'https://www.deeplearning.ai/courses/agentic-ai/',
 'Andrew Ng''s DeepLearning.AI course on building agents. A solid broad treatment of the topic.',
 'DeepLearning.AI',
 4),
('CS50''s Introduction to Artificial Intelligence with Python',
 'https://cs50.harvard.edu/ai/',
 'Harvard''s CS50 AI track on edX. The canonical computer-science intro to AI.',
 'Harvard (edX)',
 40);
