-- Seed content: Anthropic plugins, Anthropic courses, Karpathy + Anthropic articles

insert into plugins (slug, name, description, github_url, install_command, invocation_prompt, example_search, department) values
('skill-creator',
 'Skill Creator',
 'Build new Claude skills from scratch. Start here when you want to package a workflow so everyone on the team can use it. Great for turning a repeatable task into a one-liner.',
 'https://github.com/anthropics/skills/blob/main/skills/skill-creator/SKILL.md',
 '/plugin marketplace add anthropics/skills',
 'Ask Claude to "use the skill-creator skill to build me a skill that does X".',
 'Create a new skill that writes weekly supplier emails',
 'Productivity'),
('pdf',
 'PDF',
 'Read, extract, and create PDFs — forms, tables, OCR on scanned pages, merging, splitting, rotating, watermarks.',
 'https://github.com/anthropics/skills/blob/main/skills/pdf/SKILL.md',
 '/plugin marketplace add anthropics/skills',
 'Ask Claude to "extract the tables from this PDF" or "turn this markdown into a PDF".',
 'Extract the line items from this supplier invoice PDF',
 'Productivity'),
('xlsx',
 'XLSX',
 'Work with Excel files: read, edit, create. Formulas, formatting, charts, pivot tables, cleaning messy tabular data into a proper spreadsheet.',
 'https://github.com/anthropics/skills/blob/main/skills/xlsx/SKILL.md',
 '/plugin marketplace add anthropics/skills',
 'Ask Claude to "clean this spreadsheet" or "build a P&L model from this data".',
 'Clean this messy CSV and fix the date column',
 'Productivity'),
('docx',
 'DOCX',
 'Create, read, and edit Word documents — tables of contents, headings, page numbers, letterheads, tracked changes, find-and-replace.',
 'https://github.com/anthropics/skills/blob/main/skills/docx/SKILL.md',
 '/plugin marketplace add anthropics/skills',
 'Ask Claude to "turn this into a formatted Word doc" or "fix the styles in this .docx".',
 'Turn this proposal into a polished Word document',
 'Productivity'),
('pptx',
 'PPTX',
 'Build slide decks, read existing ones, extract text. Templates, layouts, speaker notes, combining and splitting files.',
 'https://github.com/anthropics/skills/blob/main/skills/pptx/SKILL.md',
 '/plugin marketplace add anthropics/skills',
 'Ask Claude to "build me a pitch deck about X" or "pull the text out of this presentation".',
 'Build an investor deck from this Notion page',
 'Productivity');

insert into courses (title, url, description, provider, estimated_hours) values
('AI Fluency: Framework & Foundations',
 'https://anthropic.skilljar.com/page/catalog',
 'The core vocabulary and mental models for working with AI. Anthropic''s official intro course — worth it even if you think you already know the basics.',
 'Anthropic',
 2),
('Prompt Engineering Interactive Tutorial',
 'https://github.com/anthropics/prompt-eng-interactive-tutorial',
 'Nine hands-on Jupyter notebooks covering every major prompting pattern. Work through them all and you''ll be in the top few percent of prompt engineers at your company.',
 'Anthropic',
 4);

insert into articles (title, url, description, author, source) values
('Software 2.0',
 'https://karpathy.medium.com/software-2-0-a64152b37c35',
 'The foundational essay: programming by curating training data, not writing code. Still the best framing of what has actually changed.',
 'Andrej Karpathy',
 'Medium'),
('Intro to Large Language Models (1-hour talk)',
 'https://www.youtube.com/watch?v=zjkBMFhNj_g',
 'If you watch one thing about LLMs, watch this. Karpathy walks through training, inference, RLHF, system prompts — the whole stack.',
 'Andrej Karpathy',
 'YouTube'),
('State of GPT — Microsoft Build 2023',
 'https://www.youtube.com/watch?v=bZQun8Y4L2A',
 'End-to-end: how GPT-style models are pretrained, supervised-fine-tuned, and aligned with RLHF. The clearest single explanation.',
 'Andrej Karpathy',
 'Microsoft Build'),
('Let''s build GPT: from scratch, in code, spelled out',
 'https://www.youtube.com/watch?v=kCc8FmEb1nY',
 'Build a transformer in Python, line by line. You don''t need an ML background to follow — just patience.',
 'Andrej Karpathy',
 'YouTube'),
('A Recipe for Training Neural Networks',
 'https://karpathy.github.io/2019/04/25/recipe/',
 'The debugging playbook every ML engineer should re-read once a year. Holds up surprisingly well in the LLM era.',
 'Andrej Karpathy',
 'karpathy.github.io'),
('Building Effective Agents',
 'https://www.anthropic.com/research/building-effective-agents',
 'Anthropic''s anti-framework take on agents: when to use them, when not to, and the small set of patterns that actually work in production.',
 'Anthropic',
 'Anthropic'),
('Claude Code Best Practices',
 'https://www.anthropic.com/engineering/claude-code-best-practices',
 'How Anthropic''s own teams use Claude Code in production. Dense with patterns you''ll want to copy.',
 'Anthropic',
 'Anthropic');
